version: "2.1"

volumes:
  hex: ~
  mix: ~

services:
  app:
    image: elixir:latest
    entrypoint: mix
    command: test
    working_dir: /code
    volumes:
      - .:/code
      - mix:/root/.mix
      - hex:/root/.hex

  mongo:
    image: mongo:latest
